name: '[T1138] Application Shimming - FileAccess'
integration: Splunk
reference: https://github.com/olafhartong/ThreatHunting
description: Hunting query based on sysmon or windows events for Splunk
author: olafhartong
mitre_technique:
  id: T1138
  datasources:
  - File monitoring
coverage:
  app:
    and: ThreatHunting
  sourcetype:
    and:
    - XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
search: '`indextime` `sysmon` event_id=11 (file_path="C:\\Windows\\AppPatch\\Custom\\*")
  \
  | eval mitre_technique_id="T1138" \
  | `file_create_whitelist`\
  | eval indextime = _indextime | convert ctime(indextime) | table _time indextime
  event_description host_fqdn process_path file_path process_guid process_id'
