name: '[T1071] Standard Application Layer Protocol'
author: olafhartong
description: Hunting query based on sysmon or windows events for Splunk
reference: https://github.com/olafhartong/ThreatHunting
integration: Splunk
mitre_technique:
  id: T1071
queries:
- '`indextime` `sysmon` event_id=22 [| inputlookup doh.csv] | eval mitre_technique_id="T1071"
  | eval event_description="DNS Query"  | `dns_whitelist` | table _time indextime
  event_description host_fqdn process_path query_name query_status query_results process_guid'
