name: '[T1117] Bypassing Application Whitelisting with Regsvr32'
author: olafhartong
description: Hunting query based on sysmon or windows events for Splunk
reference: https://github.com/olafhartong/ThreatHunting
integration: Splunk
mitre_technique:
  id: T1117
queries:
- '`indextime` ((`sysmon` event_id=1) OR (`windows-security` event_id=4688)) (process_name="regsvr32.exe"
  OR process_name="rundll32.exe" OR process_name="certutil.exe") OR process_command_line="*scrobj.dll*"\

  | eval mitre_technique_id="T1117" \

  | eval hash_sha256= lower(hash_sha256)\

  | `process_create_whitelist`\

  | eval indextime = _indextime | convert ctime(indextime) | table _time indextime
  event_description hash_sha256 host_fqdn user_name original_file_name process_path
  process_guid process_parent_path process_id process_parent_id process_command_line
  process_parent_command_line process_parent_guid'
